## Provide a name in place of kube-prometheus-stack for `app:` labels
##
nameOverride: ""

## Override the deployment namespace
##
namespaceOverride: ""

## Provide a name to substitute for the full names of resources
##
fullnameOverride: ""

global:
  host: "localhost"

launcherServer:
  enabled: true
  secretName: ""
  image:
    repository: "ghcr.io/invasor-de-fronteiras/kelbi"
    tag: "v1.2.2"
  service:
    enabled: true
    type: LoadBalancer
    port: 80

signServer:
  enabled: true
  secretName: ""
  image:
    repository: "ghcr.io/invasor-de-fronteiras/kelbi"
    tag: "v1.2.2"
  service:
    enabled: true
    type: LoadBalancer
    port: 53312

entranceServer:
  enabled: true
  secretName: ""
  type: LoadBalancer
  image:
    repository: "ghcr.io/invasor-de-fronteiras/kelbi"
    tag: "v1.2.2"
  service:
    enabled: true
    type: LoadBalancer
    port: 53310

entriesServer:
  enabled: true
  secretName: ""
  image:
    repository: "ghcr.io/invasor-de-fronteiras/kelbi"
    tag: "v1.2.2"
  service:
    enabled: true
    type: LoadBalancer
  volumes:
    - name: "bin"
      hostPath:
        path: "C:\\Users\\raina_py7xzzm\\OneDrive\\Área de Trabalho\\arca\\repos\\helm-charts\\charts\\kelbi\\volume\\bin"
        type: Directory
  volumeMounts:
    - name: "bin"
      mountPath: "/app/bin"
  entries:
    - name: "Newbie"
      description: ""
      type: 3
      recommended: 2
      allowedClientFlags: 0
      lands:
        - port: 54001
          maxPlayers: 100

    - name: "Normal"
      description: ""
      type: 1
      recommended: 0
      allowedClientFlags: 0
      lands:
        - port: 54002
          maxPlayers: 100

    - name: "Cities"
      description: ""
      type: 2
      recommended: 0
      allowedClientFlags: 0
      lands:
        - port: 54003
          maxPlayers: 100

    - name: "Tavern"
      description: ""
      type: 4
      recommended: 0
      allowedClientFlags: 0
      lands:
        - port: 54004
          maxPlayers: 100

    - name: "Return"
      description: ""
      type: 5
      recommended: 0
      allowedClientFlags: 0
      lands:
        - port: 54005
          maxPlayers: 100

    - name: "MezFes"
      description: ""
      type: 6
      recommended: 6
      allowedClientFlags: 0
      lands:
        - port: 54006
          maxPlayers: 100

postgresql:
  global:
    postgresql:
      auth:
        username: kelbi
        password: kelbi
        database: erupe
  primary:
    service:
      type: LoadBalancer
      port: 5432