## Provide a name in place of kube-prometheus-stack for `app:` labels
##
nameOverride: ""

## Override the deployment namespace
##
namespaceOverride: ""

## Provide a name to substitute for the full names of resources
##
fullnameOverride: ""

launcherServer:
  enabled: true
  secretName: "arca"
  image:
    repository: "ghcr.io/invasor-de-fronteiras/kelbi"
    tag: "v1.2.1"
  service:
    enabled: true
    type: LoadBalancer
    port: 8080

postgresql:
  global:
    postgresql:
      auth:
        username: kelbi
        password: kelbi
        database: erupe
  primary:
    service:
      type: LoadBalancer
      port: 5432