## Provide a name in place of kube-prometheus-stack for `app:` labels
##
nameOverride: ""

## Override the deployment namespace
##
namespaceOverride: ""

## Provide a name to substitute for the full names of resources
##
fullnameOverride: ""

global:
  host: "localhost"
  secretName: "kelbi-secret"

patchServer:
  en: ""
  jp: ""

launcherServer:
  enabled: true
  image:
    repository: "ghcr.io/invasor-de-fronteiras/kelbi"
    tag: "v1.2.5"
  service:
    enabled: true
    type: LoadBalancer
    port: 80
  volumes:
  volumeMounts:

signServer:
  enabled: true
  image:
    repository: "ghcr.io/invasor-de-fronteiras/kelbi"
    tag: "v1.2.5"
  service:
    enabled: true
    type: LoadBalancer
    port: 53312

entranceServer:
  enabled: true
  type: LoadBalancer
  image:
    repository: "ghcr.io/invasor-de-fronteiras/kelbi"
    tag: "v1.2.5"
  service:
    enabled: true
    type: LoadBalancer
    port: 53310

entriesServer:
  enabled: true
  image:
    repository: "ghcr.io/invasor-de-fronteiras/kelbi"
    tag: "v1.2.5"
  service:
    enabled: true
    type: LoadBalancer
  volumes:
    - name: "bin"
      hostPath:
        path: ""
        type: Directory
  volumeMounts:
    - name: "bin"
      mountPath: "/app/bin"
  entries:
    - name: "Newbie"
      description: ""
      type: 3
      recommended: 2
      allowedClientFlags: 0
      discordEnabled: false
      lands:
        - port: 54001
          maxPlayers: 100

    - name: "Normal"
      description: ""
      type: 1
      recommended: 0
      allowedClientFlags: 0
      discordEnabled: true
      lands:
        - port: 54002
          maxPlayers: 100

    - name: "Cities"
      description: ""
      type: 2
      recommended: 0
      allowedClientFlags: 0
      discordEnabled: false
      lands:
        - port: 54003
          maxPlayers: 100

    - name: "Tavern"
      description: ""
      type: 4
      recommended: 0
      allowedClientFlags: 0
      discordEnabled: false
      lands:
        - port: 54004
          maxPlayers: 100

    - name: "Return"
      description: ""
      type: 5
      recommended: 0
      allowedClientFlags: 0
      discordEnabled: false
      lands:
        - port: 54005
          maxPlayers: 100

    - name: "MezFes"
      description: ""
      type: 6
      recommended: 6
      allowedClientFlags: 0
      discordEnabled: true
      lands:
        - port: 54006
          maxPlayers: 100

postgresql:
  enabled: true
  global:
    postgresql:
      auth:
        username: kelbi
        password: kelbi
        database: erupe
  primary:
    service:
      type: LoadBalancer
      port: 5432

