---
{{- if .Values.signServer.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ template "kelbi.namespace" }}
  name: {{ template "kelbi.fullname" }}-signserver
  labels:
    app: {{ template "kelbi.name" }}-signserver
spec:
  selector:
    matchLabels:
      app: {{ template "kelbi.name" }}-signserver
  template:
    metadata:
      labels:
        app: {{ template "kelbi.name" }}-signserver
    spec:
      volumes:
        - name: configjson
          configMap:
            name: {{ template "kelbi.name" }}-config
      containers:
        - name: signserver
          image: {{ .Values.signServer.image.repository }}:{{ .Values.signServer.image.tag }}
          {{ if $.Values.global.secretName -}}
          envFrom:
            - secretRef:
                name: {{ $.Values.global.secretName }}
          {{- end }}
          env:
            - name: ERUPE_SIGN_ENABLED
              value: "true"
            - name: ERUPE_HOST
              value: {{ .Values.global.host }}
            - name: ERUPE_ENTRANCE_PORT
              value: "{{ .Values.entranceServer.service.port }}"
          volumeMounts:
            - name: configjson
              readOnly: true
              mountPath: "/etc/config"
{{- end -}}
