---
{{- if .Values.entranceServer.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ template "kelbi.namespace" }}
  name: {{ template "kelbi.fullname" }}-entranceserver
  labels:
    app: {{ template "kelbi.name" }}-entranceserver
spec:
  selector:
    matchLabels:
      app: {{ template "kelbi.name" }}-entranceserver
  template:
    metadata:
      labels:
        app: {{ template "kelbi.name" }}-entranceserver
    spec:
      volumes:
        - name: configjson
          configMap:
            name: {{ template "kelbi.name" }}-config
      containers:
        - name: entranceserver
          image: {{ .Values.entranceServer.image.repository }}:{{ .Values.entranceServer.image.tag }}
          env:
            - name: ERUPE_ENTRANCE_ENABLED
              value: "true"
            - name: ERUPE_HOST
              value: {{ .Values.global.host }}
            - name: ERUPE_DATABASE_HOST
              value: {{ template "kelbi.name" }}-postgresql
            - name: ERUPE_DATABASE_PORT
              value: "{{ .Values.postgresql.primary.service.port }}"
            - name: ERUPE_DATABASE_DATABASE
              value: {{ .Values.postgresql.global.postgresql.auth.database }}
            - name: ERUPE_DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: {{ template "kelbi.name" }}-database-secret
                  key: ERUPE_DATABASE_USER
            - name: ERUPE_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "kelbi.name" }}-database-secret
                  key: ERUPE_DATABASE_PASSWORD
  
          volumeMounts:
            - name: configjson
              readOnly: true
              mountPath: "/etc/config"
{{- end -}}