---
{{- if .Values.entranceServer.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ template "kelbi.namespace" }}
  name: {{ template "kelbi.fullname" }}-entranceserver
  labels:
    app: {{ template "kelbi.name" }}-entranceserver
spec:
  selector:
    matchLabels:
      app: {{ template "kelbi.name" }}-entranceserver
  template:
    metadata:
      labels:
        app: {{ template "kelbi.name" }}-entranceserver
    spec:
      volumes:
        - name: configjson
          configMap:
            name: {{ template "kelbi.name" }}-config
      containers:
        - name: entranceserver
          image: {{ .Values.entranceServer.image.repository }}:{{ .Values.entranceServer.image.tag }}
          {{ if .Values.global.secretName -}}
          envFrom:
            - secretRef:
                name: {{ .Values.global.secretName }}
          {{- end }}
          env:
            - name: ERUPE_ENTRANCE_ENABLED
              value: "true"
            - name: ERUPE_HOST
              value: {{ .Values.global.host }}
          volumeMounts:
            - name: configjson
              readOnly: true
              mountPath: "/etc/config"
{{- end -}}
