apiVersion: v1
kind: Secret
metadata:
  name: {{ template "kelbi.name" }}-database-secret
type: Opaque
data:
  ERUPE_DATABASE_USER: {{ .Values.postgresql.global.postgresql.auth.username | b64enc | quote }}
  ERUPE_DATABASE_PASSWORD: {{ .Values.postgresql.global.postgresql.auth.password | b64enc | quote }}
