---
{{- if .Values.launcherServer.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ template "kelbi.namespace" }}
  name: {{ template "kelbi.fullname" }}-launcherserver
  labels:
    app: {{ template "kelbi.name" }}-launcherserver
spec:
  selector:
    matchLabels:
      app: {{ template "kelbi.name" }}-launcherserver
  template:
    metadata:
      labels:
        app: {{ template "kelbi.name" }}-launcherserver
    spec:
      volumes:
        - name: configjson
          configMap:
            name: {{ template "kelbi.name" }}-config
      containers:
        - name: launcherserver
          image: {{ .Values.launcherServer.image.repository }}:{{ .Values.launcherServer.image.tag }}
          {{ if $.Values.global.secretName -}}
          envFrom:
            - secretRef:
                name: {{ $.Values.global.secretName }}
          {{- end }}
          env:
            - name: ERUPE_LAUNCHER_ENABLED
              value: "true"
            - name: ERUPE_HOST
              value: {{ .Values.global.host }}
            - name: ERUPE_SIGN_PORT
              value: "{{ .Values.signServer.service.port }}"
            - name: ERUPE_PATCHSERVERS_EN_PATCHSERVERFILE
              value: "{{ .Values.patchServer.en }}"
            - name: ERUPE_PATCHSERVERS_EN_PATCHSERVERMANIFEST
              value: "{{ .Values.patchServer.en }}"
            - name: ERUPE_PATCHSERVERS_JP_PATCHSERVERFILE
              value: "{{ .Values.patchServer.jp }}"
            - name: ERUPE_PATCHSERVERS_JP_PATCHSERVERMANIFEST
              value: "{{ .Values.patchServer.jp }}"
          volumeMounts:
            - name: configjson
              readOnly: true
              mountPath: "/etc/config"
{{- end -}}