---
{{- if .Values.entriesServer.service.enabled }}
{{- $values := .Values -}}
{{- range $serverIndex, $server := .Values.entriesServer.entries }}
{{- range $landIndex, $land := $server.lands }}
{{- $serverId := add $serverIndex 1 | toString }}
{{- $landId := add $landIndex 1 | toString }}
---
apiVersion: v1
kind: Service
metadata:
  namespace: {{ template "kelbi.namespace" }}
  name: {{ template "kelbi.fullname" }}-channel-{{ $serverId }}-{{ $landId }}
  labels:
    app: {{ template "kelbi.name" }}-channel-{{ $serverId }}-{{ $landId }}
spec:
  type: {{ $values.entriesServer.service.type }}
  ports:
    - port: {{ $land.port }}
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: {{ template "kelbi.name" }}-channel-{{ $serverId }}-{{ $landId }}
{{- end -}}
{{- end -}}
{{- end -}}