apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "erupe.name" . }}-config
  namespace: {{ template "erupe.namespace" . }}
data:
  config.json: |
    {{- .Values.config | toJson | nindent 4 }}
